/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.steamdata.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Game service. Represents a row in the &quot;Liferay_Game&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.steamdata.model.impl.GameModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.steamdata.model.impl.GameImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Game
 * @generated
 */
@ProviderType
public interface GameModel extends BaseModel<Game> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a game model instance should use the {@link Game} interface instead.
	 */

	/**
	 * Returns the primary key of this game.
	 *
	 * @return the primary key of this game
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this game.
	 *
	 * @param primaryKey the primary key of this game
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the app ID of this game.
	 *
	 * @return the app ID of this game
	 */
	public long getAppId();

	/**
	 * Sets the app ID of this game.
	 *
	 * @param appId the app ID of this game
	 */
	public void setAppId(long appId);

	/**
	 * Returns the publisher ID of this game.
	 *
	 * @return the publisher ID of this game
	 */
	@AutoEscape
	public String getPublisherId();

	/**
	 * Sets the publisher ID of this game.
	 *
	 * @param publisherId the publisher ID of this game
	 */
	public void setPublisherId(String publisherId);

	/**
	 * Returns the title of this game.
	 *
	 * @return the title of this game
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this game.
	 *
	 * @param title the title of this game
	 */
	public void setTitle(String title);

	/**
	 * Returns the release date of this game.
	 *
	 * @return the release date of this game
	 */
	public Date getReleaseDate();

	/**
	 * Sets the release date of this game.
	 *
	 * @param releaseDate the release date of this game
	 */
	public void setReleaseDate(Date releaseDate);

	/**
	 * Returns the price of this game.
	 *
	 * @return the price of this game
	 */
	public double getPrice();

	/**
	 * Sets the price of this game.
	 *
	 * @param price the price of this game
	 */
	public void setPrice(double price);

	/**
	 * Returns the about description of this game.
	 *
	 * @return the about description of this game
	 */
	@AutoEscape
	public String getAboutDescription();

	/**
	 * Sets the about description of this game.
	 *
	 * @param aboutDescription the about description of this game
	 */
	public void setAboutDescription(String aboutDescription);

	@Override
	public Game cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}