/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.steamdata.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.steamdata.model.Game;
import com.liferay.steamdata.model.GameModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Game service. Represents a row in the &quot;Liferay_Game&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>GameModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GameImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GameImpl
 * @generated
 */
public class GameModelImpl extends BaseModelImpl<Game> implements GameModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a game model instance should use the <code>Game</code> interface instead.
	 */
	public static final String TABLE_NAME = "Liferay_Game";

	public static final Object[][] TABLE_COLUMNS = {
		{"appId", Types.BIGINT}, {"publisherId", Types.VARCHAR},
		{"title", Types.VARCHAR}, {"releaseDate", Types.TIMESTAMP},
		{"price", Types.DOUBLE}, {"aboutDescription", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("appId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("publisherId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("releaseDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("price", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("aboutDescription", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Liferay_Game (appId LONG not null primary key,publisherId VARCHAR(75) null,title VARCHAR(75) null,releaseDate DATE null,price DOUBLE,aboutDescription VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table Liferay_Game";

	public static final String ORDER_BY_JPQL = " ORDER BY game.appId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Liferay_Game.appId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public GameModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _appId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAppId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _appId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Game.class;
	}

	@Override
	public String getModelClassName() {
		return Game.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Game, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Game, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Game, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Game)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Game, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Game, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Game)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Game, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Game, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Game, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Game, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Game, Object>>();

			attributeGetterFunctions.put("appId", Game::getAppId);
			attributeGetterFunctions.put("publisherId", Game::getPublisherId);
			attributeGetterFunctions.put("title", Game::getTitle);
			attributeGetterFunctions.put("releaseDate", Game::getReleaseDate);
			attributeGetterFunctions.put("price", Game::getPrice);
			attributeGetterFunctions.put(
				"aboutDescription", Game::getAboutDescription);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Game, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Game, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Game, ?>>();

			attributeSetterBiConsumers.put(
				"appId", (BiConsumer<Game, Long>)Game::setAppId);
			attributeSetterBiConsumers.put(
				"publisherId", (BiConsumer<Game, String>)Game::setPublisherId);
			attributeSetterBiConsumers.put(
				"title", (BiConsumer<Game, String>)Game::setTitle);
			attributeSetterBiConsumers.put(
				"releaseDate", (BiConsumer<Game, Date>)Game::setReleaseDate);
			attributeSetterBiConsumers.put(
				"price", (BiConsumer<Game, Double>)Game::setPrice);
			attributeSetterBiConsumers.put(
				"aboutDescription",
				(BiConsumer<Game, String>)Game::setAboutDescription);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getAppId() {
		return _appId;
	}

	@Override
	public void setAppId(long appId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appId = appId;
	}

	@Override
	public String getPublisherId() {
		if (_publisherId == null) {
			return "";
		}
		else {
			return _publisherId;
		}
	}

	@Override
	public void setPublisherId(String publisherId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_publisherId = publisherId;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@Override
	public Date getReleaseDate() {
		return _releaseDate;
	}

	@Override
	public void setReleaseDate(Date releaseDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_releaseDate = releaseDate;
	}

	@Override
	public double getPrice() {
		return _price;
	}

	@Override
	public void setPrice(double price) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_price = price;
	}

	@Override
	public String getAboutDescription() {
		if (_aboutDescription == null) {
			return "";
		}
		else {
			return _aboutDescription;
		}
	}

	@Override
	public void setAboutDescription(String aboutDescription) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_aboutDescription = aboutDescription;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Game.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Game toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Game>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GameImpl gameImpl = new GameImpl();

		gameImpl.setAppId(getAppId());
		gameImpl.setPublisherId(getPublisherId());
		gameImpl.setTitle(getTitle());
		gameImpl.setReleaseDate(getReleaseDate());
		gameImpl.setPrice(getPrice());
		gameImpl.setAboutDescription(getAboutDescription());

		gameImpl.resetOriginalValues();

		return gameImpl;
	}

	@Override
	public Game cloneWithOriginalValues() {
		GameImpl gameImpl = new GameImpl();

		gameImpl.setAppId(this.<Long>getColumnOriginalValue("appId"));
		gameImpl.setPublisherId(
			this.<String>getColumnOriginalValue("publisherId"));
		gameImpl.setTitle(this.<String>getColumnOriginalValue("title"));
		gameImpl.setReleaseDate(
			this.<Date>getColumnOriginalValue("releaseDate"));
		gameImpl.setPrice(this.<Double>getColumnOriginalValue("price"));
		gameImpl.setAboutDescription(
			this.<String>getColumnOriginalValue("aboutDescription"));

		return gameImpl;
	}

	@Override
	public int compareTo(Game game) {
		long primaryKey = game.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Game)) {
			return false;
		}

		Game game = (Game)object;

		long primaryKey = game.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Game> toCacheModel() {
		GameCacheModel gameCacheModel = new GameCacheModel();

		gameCacheModel.appId = getAppId();

		gameCacheModel.publisherId = getPublisherId();

		String publisherId = gameCacheModel.publisherId;

		if ((publisherId != null) && (publisherId.length() == 0)) {
			gameCacheModel.publisherId = null;
		}

		gameCacheModel.title = getTitle();

		String title = gameCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			gameCacheModel.title = null;
		}

		Date releaseDate = getReleaseDate();

		if (releaseDate != null) {
			gameCacheModel.releaseDate = releaseDate.getTime();
		}
		else {
			gameCacheModel.releaseDate = Long.MIN_VALUE;
		}

		gameCacheModel.price = getPrice();

		gameCacheModel.aboutDescription = getAboutDescription();

		String aboutDescription = gameCacheModel.aboutDescription;

		if ((aboutDescription != null) && (aboutDescription.length() == 0)) {
			gameCacheModel.aboutDescription = null;
		}

		return gameCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Game, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Game, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Game, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Game)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Game>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Game.class, ModelWrapper.class);

	}

	private long _appId;
	private String _publisherId;
	private String _title;
	private Date _releaseDate;
	private double _price;
	private String _aboutDescription;

	public <T> T getColumnValue(String columnName) {
		Function<Game, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Game)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("appId", _appId);
		_columnOriginalValues.put("publisherId", _publisherId);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("releaseDate", _releaseDate);
		_columnOriginalValues.put("price", _price);
		_columnOriginalValues.put("aboutDescription", _aboutDescription);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("appId", 1L);

		columnBitmasks.put("publisherId", 2L);

		columnBitmasks.put("title", 4L);

		columnBitmasks.put("releaseDate", 8L);

		columnBitmasks.put("price", 16L);

		columnBitmasks.put("aboutDescription", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Game _escapedModel;

}